### ISSUE TITLE
Failed to authenticate when downloading repository

### ISSUE THREAD

**Issue by Dgame** [vvilhonen/cargo-aws-lambda#2]
Hi, I tried to use your project in one of my github action workflows, but since my lambda uses private dependencies, I got the error
> failed to authenticate when downloading repository

Do you know a possible solution?

**Comment by Dgame** [comment]
I don't know how useful it is, but to test my lambda I use [fusion-engineering/setup-git-credential](https://github.com/fusion-engineering/setup-git-credentials) in my workflow.

**Comment by vvilhonen** [comment]
Hi! Could you describe a bit more which exact commands you're running before the error occurs and how the config looks like? Did I understand correctly that you're able to build your project with private dependencies, but not with cargo-aws-lambda somehow?

**Comment by Dgame** [comment]
I solved the problem by now using the cache of previous jobs. Otherwise an ssh key or github credentials would be required to clone certain repositories.
